const terms = [
["Acero de refuerzo","Estructura","Barras metálicas que se colocan dentro del hormigón para aumentar su resistencia a la tracción."],
["Aditivo","Materiales","Producto químico que se añade al hormigón o mortero para modificar sus propiedades."],
["Aislación acústica","Terminaciones","Sistema o material que reduce la transmisión de ruido entre recintos."],
["Aislación térmica","Terminaciones","Material o sistema que reduce el paso de calor entre interior y exterior."],
["Albañilería","Estructura","Sistema constructivo basado en unidades como ladrillo o bloque, unidas con mortero."],
["Alero","Estructura","Prolongación del techo que sobresale de la fachada, protege muros y vanos."],
["Alicatado","Terminaciones","Revestimiento de un muro con azulejos o cerámicas."],
["Alineación","Medidas y trazado","Correcta disposición de elementos constructivos en una misma línea o plano."],
["Alza","Faena y obra","Elemento que eleva o nivela otro componente, como una base para pilares."],
["Amasado","Faena y obra","Proceso de mezclar cemento, arena, agua y áridos para obtener mortero u hormigón."],
["Amperímetro","Instalaciones","Instrumento que mide la corriente eléctrica en un circuito."],
["Anclaje","Estructura","Elemento que fija una pieza estructural a otra o al suelo, resistiendo tracción o corte."],
["Andamio","Faena y obra","Estructura provisoria que permite trabajar en altura de forma segura."],
["Antepecho","Estructura","Muro bajo bajo una ventana o en el borde de una terraza, sirve de protección."],
["Aplomado","Medidas y trazado","Verificación de que un elemento está perfectamente vertical."],
["Aparejo","Estructura","Forma en que se disponen los ladrillos o bloques en un muro de albañilería."],
["Arco","Estructura","Elemento estructural curvo que transmite cargas a los apoyos por compresión."],
["Armadura","Estructura","Conjunto de barras de acero dispuestas para reforzar un elemento de hormigón."],
["Arriostramiento","Estructura","Elemento diagonal que da rigidez a una estructura y evita su deformación lateral."],
["Asentamiento","Fundaciones","Descenso que sufre una construcción o su terreno de fundación con el tiempo."],
["Bajada de aguas lluvias","Instalaciones","Tubería que conduce el agua de lluvia desde la canaleta hasta el suelo."],
["Baldosa","Terminaciones","Pieza de revestimiento para pisos o muros, de cerámica, hormigón u otro material."],
["Bandeja eléctrica","Instalaciones","Estructura metálica que soporta y ordena cables eléctricos en una instalación."],
["Barra corrugada","Estructura","Barra de acero con resaltes que mejora su adherencia con el hormigón."],
["Barrera de humedad","Fundaciones","Membrana o material que impide el paso de humedad desde el suelo."],
["Berma","Medidas y trazado","Franja de terreno entre la calzada y la vereda, o talud lateral en movimientos de tierra."],
["Bisagra","Terminaciones","Herraje que permite el giro de una puerta o ventana sobre su marco."],
["Bitácora de obra","Faena y obra","Registro diario de avances, incidencias e instrucciones durante la construcción."],
["Bloque de hormigón","Estructura","Unidad prefabricada de hormigón usada en albañilería."],
["Bomba de agua","Maquinaria","Equipo que impulsa agua a presión dentro de una instalación o faena."],
["Bovedilla","Estructura","Elemento prefabricado que se coloca entre viguetas para formar losas de entrepiso."],
["Disyuntor","Instalaciones","Interruptor automático que corta el paso de corriente ante una sobrecarga; también conocido coloquialmente como 'breaker'."],
["Broca","Herramientas","Pieza cortante que se acopla a un taladro para perforar distintos materiales."],
["Cadena","Estructura","Elemento horizontal de hormigón armado que amarra los muros y distribuye cargas."],
["Cala","Faena y obra","Excavación exploratoria para verificar el terreno o una instalación existente."],
["Calafateo","Terminaciones","Sellado de juntas con masilla o silicona para evitar filtraciones."],
["Caldera","Instalaciones","Equipo que calienta agua para calefacción o agua caliente sanitaria."],
["Canaleta","Instalaciones","Elemento que recoge el agua de lluvia en el borde del techo."],
["Cañería","Instalaciones","Tubería utilizada para conducir agua, gas u otros fluidos."],
["Capa de rodadura","Pavimentos","Capa superficial de un pavimento sobre la que circulan vehículos o peatones."],
["Carga muerta","Estructura","Peso propio de los elementos permanentes de una construcción."],
["Carga viva","Estructura","Peso variable que soporta una estructura, como personas o muebles."],
["Carretilla","Herramientas","Vehículo manual de una rueda usado para transportar materiales en obra."],
["Cartabón","Herramientas","Herramienta con forma de triángulo rectángulo usada para trazar ángulos."],
["Cepillo de carpintero","Herramientas","Herramienta manual para alisar y dar forma a superficies de madera."],
["Cepo","Faena y obra","Pieza que fija o retiene un elemento en su posición, como en moldajes."],
["Cercha","Estructura","Estructura triangulada que sostiene la cubierta de un techo."],
["Cimiento","Fundaciones","Elemento bajo tierra que transmite las cargas de la construcción al terreno."],
["Cielo falso","Terminaciones","Revestimiento suspendido bajo la losa o estructura que oculta instalaciones."],
["Cielo raso","Terminaciones","Superficie que cubre la parte superior de un recinto, visible desde el interior."],
["Cinta métrica","Herramientas","Instrumento flexible usado para medir distancias en obra."],
["Codo","Instalaciones","Pieza de cañería que permite cambiar la dirección de una tubería."],
["Colector","Instalaciones","Ducto o cañería que reúne el flujo de varias tuberías secundarias."],
["Compactación","Faena y obra","Proceso mecánico que densifica un suelo o material de relleno."],
["Compresor","Maquinaria","Equipo que suministra aire a presión para herramientas neumáticas."],
["Contactor","Instalaciones","Dispositivo eléctrico que permite controlar el encendido de motores o cargas."],
["Contrapiso","Terminaciones","Capa de hormigón o mortero que nivela el piso antes del revestimiento final."],
["Corte y relleno","Fundaciones","Movimiento de tierra que combina excavación en un sector y relleno en otro."],
["Cota","Medidas y trazado","Valor numérico que indica una altura o nivel de referencia en los planos."],
["Cuadrilla","Faena y obra","Grupo de trabajadores asignado a una tarea específica en la obra."],
["Cubierta","Estructura","Elemento superior de una edificación que la protege de la intemperie."],
["Curado","Faena y obra","Proceso de mantener húmedo el hormigón tras el vaciado para alcanzar resistencia final."],
["Chapa","Terminaciones","Cerradura o mecanismo de cierre de una puerta."],
["Chicote","Instalaciones","Tramo corto de cable o manguera usado para conexiones puntuales en obra."],
["Descimbre","Faena y obra","Retiro del moldaje una vez que el hormigón alcanza resistencia suficiente."],
["Desnivel","Medidas y trazado","Diferencia de altura entre dos puntos o superficies."],
["Detector de metales","Herramientas","Instrumento que localiza barras de acero u otros metales dentro de un elemento."],
["Diafragma","Estructura","Elemento plano que distribuye cargas horizontales, como sismos, a elementos verticales."],
["Doble altura","Diseño","Espacio interior que abarca dos pisos sin entrepiso intermedio."],
["Draga","Maquinaria","Excavadora usada para extraer material desde el fondo de cursos de agua."],
["Ducto","Instalaciones","Conducto que alberga instalaciones eléctricas, sanitarias o de ventilación."],
["EPP","Seguridad","Elementos de Protección Personal: casco, guantes, lentes, arnés, entre otros."],
["Empalme","Instalaciones","Conexión entre dos tramos de un mismo elemento, como cañerías o cables."],
["Emplantillado","Fundaciones","Capa de hormigón pobre que se coloca antes de la fundación para nivelar el terreno."],
["Enchape","Terminaciones","Revestimiento decorativo aplicado sobre un muro o superficie."],
["Enfierradura","Estructura","Armado de barras de acero que refuerza el hormigón antes de vaciarlo."],
["Enlucido","Terminaciones","Terminación fina aplicada sobre un revoque o estuco."],
["Enrase","Medidas y trazado","Nivelación de una superficie hasta quedar a ras de otra referencia."],
["Entablado","Terminaciones","Revestimiento de piso o muro hecho con tablas de madera."],
["Entramado","Estructura","Conjunto de piezas de madera o metal que forman la estructura de un tabique o piso."],
["Entrepiso","Estructura","Losa o estructura que separa dos niveles de una edificación."],
["Escala de faena","Faena y obra","Programa que ordena las etapas de construcción en el tiempo."],
["Escuadra","Medidas y trazado","Ángulo recto entre dos elementos; también la herramienta para verificarlo."],
["Estuco","Terminaciones","Revestimiento de mortero aplicado sobre muros para emparejar y proteger la superficie."],
["Excavación","Fundaciones","Remoción de tierra o roca para preparar fundaciones o instalaciones."],
["Excavadora","Maquinaria","Máquina que remueve tierra o material mediante un brazo con cuchara."],
["Extintor","Seguridad","Equipo portátil usado para combatir incendios incipientes en obra."],
["Faena","Faena y obra","Trabajo o actividad específica dentro de la obra, o la obra misma en su conjunto."],
["Falsa escuadra","Herramientas","Herramienta ajustable para transportar o verificar ángulos distintos al recto."],
["Fibra de vidrio","Materiales","Material aislante o de refuerzo compuesto por filamentos de vidrio."],
["Filtración","Terminaciones","Paso no deseado de agua a través de un elemento constructivo."],
["Fisura","Estructura","Grieta fina superficial que no compromete la estabilidad estructural."],
["Fraguado","Faena y obra","Proceso químico por el cual el cemento endurece y adquiere resistencia. Se distingue el fraguado inicial (aprox. 4 horas) del fraguado final (entre 4 y 10 horas); la ganancia de resistencia comienza cerca de las 10 horas y continúa indefinidamente, aunque estructuralmente el hormigón se considera cargable a partir de los 28 días."],
["Fundación","Fundaciones","Elemento que transmite el peso de la estructura al terreno."],
["Galvanizado","Materiales","Recubrimiento de zinc aplicado al acero para protegerlo de la corrosión."],
["Geomalla","Materiales","Material sintético usado para reforzar o estabilizar terrenos."],
["Geotextil","Materiales","Tejido sintético que separa capas de suelo permitiendo el paso de agua."],
["Grieta","Estructura","Abertura visible en un elemento constructivo, puede ser superficial o estructural."],
["Grúa torre","Maquinaria","Equipo de elevación fijo usado para mover materiales en obras de altura."],
["Guardapolvo","Terminaciones","Moldura colocada en la base del muro para proteger de golpes y polvo."],
["Herraje","Terminaciones","Pieza metálica funcional como bisagras, cerraduras o manillas."],
["Hidrofugo","Materiales","Aditivo o tratamiento que reduce la absorción de agua en un material."],
["Hormigón","Materiales","Mezcla de cemento, agua, arena y áridos que endurece formando un material resistente."],
["Hormigón armado","Estructura","Hormigón reforzado con barras de acero para resistir tracción."],
["Hormigonera","Maquinaria","Máquina que mezcla los componentes del hormigón en obra."],
["Impermeabilización","Terminaciones","Tratamiento para evitar el paso de agua o humedad en techos, muros o fundaciones."],
["Inspección técnica de obra (ITO)","Faena y obra","Profesional que supervisa el cumplimiento del proyecto y la normativa en obra."],
["Instalación eléctrica","Instalaciones","Conjunto de cables, tableros y dispositivos que distribuyen energía en una edificación."],
["Instalación sanitaria","Instalaciones","Conjunto de tuberías y artefactos para agua potable y alcantarillado."],
["Junta de dilatación","Terminaciones","Espacio dejado entre elementos para permitir su movimiento por temperatura."],
["Junta de hormigonado","Faena y obra","Línea donde se detiene y reinicia el vaciado de hormigón en distintas etapas."],
["Ladrillo","Materiales","Unidad de albañilería fabricada de arcilla cocida u hormigón."],
["Lechada","Materiales","Mezcla fluida de cemento y agua usada para sellar juntas o rellenar espacios finos."],
["Llave de paso","Instalaciones","Dispositivo que permite cortar el flujo de agua en un punto de la red."],
["Losa","Estructura","Elemento plano de hormigón que forma pisos, techos o entrepisos."],
["Luminaria","Instalaciones","Equipo que aloja una o más fuentes de luz artificial."],
["Luz","Medidas y trazado","Distancia libre entre dos apoyos de un elemento estructural."],
["Machón","Estructura","Porción de muro entre dos vanos, como entre dos ventanas."],
["Maestranza","Faena y obra","Taller donde se fabrican o reparan piezas metálicas para la obra."],
["Maestro","Faena y obra","Trabajador con experiencia y oficio específico que ejecuta labores técnicas en terreno."],
["Malla Acma","Estructura","Malla de acero electrosoldada usada para reforzar losas y radieres."],
["Mampostería","Estructura","Construcción con piezas unidas por mortero, sinónimo de albañilería."],
["Manómetro","Instalaciones","Instrumento que mide la presión de un fluido dentro de una instalación."],
["Marco","Terminaciones","Estructura que sostiene una puerta o ventana dentro del vano."],
["Martillo demoledor","Maquinaria","Herramienta que rompe hormigón o roca mediante impacto percutivo."],
["Membrana asfáltica","Materiales","Lámina impermeabilizante a base de asfalto usada en techos y fundaciones."],
["Mezcladora","Maquinaria","Equipo que combina mecánicamente los componentes de un mortero u hormigón."],
["Mortero","Materiales","Mezcla de cemento, arena y agua usada para pegar unidades o revestir superficies."],
["Muro cortina","Estructura","Fachada no estructural, generalmente de vidrio y aluminio, colgada de la estructura."],
["Muro de contención","Fundaciones","Estructura que resiste el empuje de un talud o relleno de tierra."],
["Nivel de burbuja","Herramientas","Instrumento que indica si una superficie está horizontal o vertical."],
["Nivel láser","Herramientas","Instrumento que proyecta una línea de referencia horizontal o vertical mediante láser."],
["Nivelación","Medidas y trazado","Proceso de igualar alturas de una superficie o terreno."],
["Nudo estructural","Estructura","Punto donde se conectan dos o más elementos estructurales."],
["Obra falsa","Faena y obra","Estructura temporal que sostiene un elemento mientras se construye."],
["Obra gruesa","Faena y obra","Etapa de construcción que incluye fundaciones, estructura y cierres, sin terminaciones."],
["Pandereta","Estructura","Albañilería con ladrillos colocados de canto, usada en muros no estructurales."],
["Pasada de instalación","Instalaciones","Perforación o hueco dejado para el paso de tuberías o cables."],
["Pavimento","Pavimentos","Capa final de un piso o vía, destinada al tránsito."],
["Perfil metálico","Estructura","Pieza de acero laminado o plegado usada en estructuras y tabiques."],
["Pie derecho","Estructura","Elemento vertical de un tabique, entre la solera inferior y superior."],
["Pilar","Estructura","Elemento vertical que soporta cargas de la estructura hacia la fundación."],
["Pilote","Fundaciones","Elemento de fundación profunda que transmite cargas a estratos resistentes del suelo."],
["Pintura anticorrosiva","Materiales","Recubrimiento que protege elementos metálicos de la oxidación."],
["Placa","Terminaciones","Panel de yeso, cemento u OSB usado para revestir tabiques o cielos."],
["Plano de detalle","Normativa e instituciones","Documento gráfico que muestra información constructiva específica de un punto."],
["Plano de planta","Normativa e instituciones","Vista superior de una edificación que muestra la distribución de espacios."],
["Plomo","Medidas y trazado","Verticalidad perfecta de un elemento, verificada con hilo y peso o nivel láser."],
["Poza de decantación","Instalaciones","Excavación que retiene sedimentos antes de que el agua siga su curso."],
["Prevención de riesgos","Seguridad","Disciplina orientada a identificar y controlar peligros en obra."],
["Puente térmico","Terminaciones","Zona de una construcción con mayor pérdida de calor por discontinuidad del aislante."],
["Pretil","Estructura","Muro bajo de protección en el borde de una terraza, azotea o balcón."],
["Radier","Fundaciones","Losa de hormigón vaciada directo sobre el terreno, típica en pisos de primer nivel."],
["Rasante","Medidas y trazado","Nivel de referencia del terreno natural o de una vía."],
["Recibo de obra","Faena y obra","Acto formal en que el mandante acepta la obra terminada según lo contratado."],
["Refuerzo","Estructura","Elemento adicional que aumenta la capacidad resistente de una estructura."],
["Relleno estructural","Fundaciones","Material compactado usado para nivelar o dar soporte bajo una fundación o pavimento."],
["Repisa","Terminaciones","Elemento horizontal saliente que sirve de apoyo o remate, como bajo una ventana."],
["Resistencia a la compresión","Materiales","Capacidad de un material de soportar cargas que tienden a aplastarlo."],
["Retroexcavadora","Maquinaria","Máquina con brazo articulado usada para excavar y cargar material."],
["Revestimiento","Terminaciones","Capa final que cubre y protege una superficie constructiva."],
["Revoque","Terminaciones","Capa de mortero aplicada sobre un muro antes del estuco o pintura final."],
["Rodapié","Terminaciones","Ver zócalo; moldura que remata la unión entre el muro y el piso."],
["Rodillo compactador","Maquinaria","Máquina que compacta suelos o pavimentos mediante presión de rodillo."],
["Sello de silicona","Materiales","Producto usado para sellar juntas y evitar filtraciones de agua o aire."],
["Sifón","Instalaciones","Dispositivo sanitario que retiene agua para evitar el paso de malos olores."],
["Sobrecarga","Estructura","Peso adicional no permanente que puede afectar a una estructura."],
["Sobrecimiento","Fundaciones","Elemento de hormigón sobre el cimiento y bajo el muro, protege de la humedad del suelo."],
["Solera","Estructura","Pieza horizontal sobre la que se apoyan los pies derechos de un tabique."],
["Soldadura","Faena y obra","Proceso que une piezas metálicas mediante fusión con calor."],
["Subestación eléctrica","Instalaciones","Instalación que transforma y distribuye energía eléctrica a un edificio o conjunto."],
["Subrasante","Pavimentos","Capa de suelo natural sobre la que se apoya la estructura de un pavimento."],
["Tabique","Estructura","Muro divisorio no estructural, de madera o metalcón con revestimiento."],
["Taladro percutor","Herramientas","Herramienta que perfora combinando rotación e impacto, usada en hormigón y albañilería."],
["Talud","Fundaciones","Superficie inclinada de un terreno resultante de un corte o relleno."],
["Tapa registro","Instalaciones","Elemento removible que permite acceder a una cámara o ducto de instalaciones."],
["Tensor","Estructura","Elemento que trabaja a tracción para dar estabilidad a una estructura."],
["Terraplén","Fundaciones","Relleno de tierra compactada usado para elevar un nivel de terreno."],
["Termofusión","Instalaciones","Método de unión de tuberías plásticas mediante calor."],
["Trazado","Medidas y trazado","Marcado en terreno de las líneas y puntos que definen la ubicación de la obra."],
["Vano","Estructura","Abertura en un muro destinada a una puerta o ventana."],
["Vaciado","Faena y obra","Acción de verter hormigón fresco en moldajes o excavaciones."],
["Vereda","Pavimentos","Superficie peatonal pavimentada al costado de una calzada."],
["Vibrador de hormigón","Maquinaria","Equipo que elimina burbujas de aire del hormigón fresco mediante vibración."],
["Viga","Estructura","Elemento horizontal que soporta cargas y las transmite a los apoyos verticales."],
["Vigueta","Estructura","Elemento estructural secundario que soporta el entrepiso o la cubierta."],
["Yeso cartón","Terminaciones","Placa de yeso revestida en cartón, usada para tabiques y cielos."],
["Zanja","Fundaciones","Excavación estrecha y alargada, usada para fundaciones corridas o instalaciones."],
["Zapata","Fundaciones","Ensanche de la base de la fundación que reparte la carga en mayor superficie de suelo."],
["Zócalo","Terminaciones","Moldura o remate en la base del muro, límite entre el muro y el piso."],
["AASHTO","Normativa e instituciones","American Association of State Highway and Transportation Officials; entidad estadounidense cuyas normas de diseño vial y de pavimentos se usan como referencia técnica en Chile."],
["Aprobación de proyecto","Normativa e instituciones","Visación que otorga la Dirección de Obras Municipales a los planos antes de emitir el permiso de edificación."],
["Certificado de informaciones previas (CIP)","Normativa e instituciones","Documento municipal que indica las normas urbanísticas aplicables a un predio antes de proyectar."],
["CChC","Normativa e instituciones","Cámara Chilena de la Construcción; gremio que agrupa a empresas del sector construcción en Chile."],
["DGA","Normativa e instituciones","Dirección General de Aguas, dependiente del MOP, encargada de administrar los derechos de agua en Chile."],
["DOM","Normativa e instituciones","Dirección de Obras Municipales; unidad de cada municipio que otorga permisos de edificación y recepciones de obra."],
["DS","Normativa e instituciones","Decreto Supremo; norma legal emitida por un ministerio que reglamenta o complementa una ley, como el DS 47 (OGUC)."],
["INN","Normativa e instituciones","Instituto Nacional de Normalización; organismo chileno que elabora y oficializa las normas técnicas NCh."],
["LGUC","Normativa e instituciones","Ley General de Urbanismo y Construcciones; ley marco que regula la planificación urbana y la edificación en Chile."],
["Mandante","Normativa e instituciones","Persona natural o jurídica que encarga y financia la ejecución de una obra."],
["MINVU","Normativa e instituciones","Ministerio de Vivienda y Urbanismo; entidad rectora de la política habitacional y urbana en Chile."],
["MOP","Normativa e instituciones","Ministerio de Obras Públicas; a cargo de infraestructura vial, hídrica, portuaria y aeroportuaria del país."],
["NCh","Normativa e instituciones","Norma Chilena; estándar técnico oficial elaborado por el INN, como NCh433 (diseño sísmico) o NCh170 (hormigón)."],
["Obras civiles","Normativa e instituciones","Infraestructura de uso público como caminos, puentes o embalses, generalmente a cargo del MOP."],
["OGUC","Normativa e instituciones","Ordenanza General de Urbanismo y Construcciones; reglamento que detalla la aplicación de la LGUC."],
["Permiso de edificación","Normativa e instituciones","Autorización municipal previa que habilita el inicio legal de una obra."],
["Plan regulador comunal","Normativa e instituciones","Instrumento de planificación territorial que define usos de suelo y normas urbanísticas de una comuna."],
["Recepción municipal","Normativa e instituciones","Trámite que certifica que la obra terminó conforme al permiso y la normativa vigente."],
["RIDAA","Normativa e instituciones","Reglamento de Instalaciones Domiciliarias de Agua Potable y Alcantarillado; regula estas instalaciones en Chile."],
["SEC","Normativa e instituciones","Superintendencia de Electricidad y Combustibles; fiscaliza instalaciones eléctricas, de gas y combustibles."],
["SEREMI MINVU","Normativa e instituciones","Secretaría Regional Ministerial de Vivienda y Urbanismo; representa al MINVU en cada región."],
["SERVIU","Normativa e instituciones","Servicio de Vivienda y Urbanización; ejecuta la política habitacional y de urbanización del MINVU en las regiones."],
["SISS","Normativa e instituciones","Superintendencia de Servicios Sanitarios; fiscaliza a las empresas de agua potable y alcantarillado."],
["Subcontrato","Normativa e instituciones","Contrato mediante el cual el contratista principal encarga parte de la obra a otra empresa especializada."],
["Zonificación","Normativa e instituciones","División del territorio urbano en zonas con usos y normas de edificación específicas, definida en el plan regulador."],
["ACHS","Normativa e instituciones","Asociación Chilena de Seguridad; organismo administrador de la ley de accidentes del trabajo y enfermedades profesionales."],
["Contraloría General de la República","Normativa e instituciones","Órgano que fiscaliza la legalidad de los actos de la administración, incluida la inversión en obras públicas."],
["ChileCompra","Normativa e instituciones","Plataforma estatal donde se licitan y adjudican contratos de obras y servicios públicos."],
["Dirección de Arquitectura MOP","Normativa e instituciones","Unidad del MOP encargada de proyectar y construir edificación pública."],
["Dirección de Vialidad","Normativa e instituciones","Unidad del MOP responsable de la red de caminos y puentes del país."],
["Dirección del Trabajo (DT)","Normativa e instituciones","Organismo que fiscaliza el cumplimiento de la legislación laboral en las obras."],
["GORE","Normativa e instituciones","Gobierno Regional; entidad que financia y prioriza inversión pública, incluida infraestructura, a nivel regional."],
["IST","Normativa e instituciones","Instituto de Seguridad del Trabajo; organismo administrador de la ley de accidentes laborales."],
["Mutual de Seguridad","Normativa e instituciones","Organismo administrador de la ley de accidentes del trabajo, presta salud laboral y prevención de riesgos."],
["SENCE","Normativa e instituciones","Servicio Nacional de Capacitación y Empleo; administra la franquicia tributaria de cursos para trabajadores."],
["SUSESO","Normativa e instituciones","Superintendencia de Seguridad Social; fiscaliza a las mutuales y el sistema de accidentes del trabajo."],
["Ayudante","Roles de obra","Trabajador que apoya a un maestro u oficial en tareas de menor especialización dentro de la faena."],
["Albañil","Roles de obra","Trabajador especializado en levantar muros y estructuras de ladrillo, bloque u hormigón."],
["Administrador de obra","Roles de obra","Profesional a cargo de la gestión global de recursos, plazos y costos de una obra."],
["Arquitecto","Roles de obra","Profesional que diseña el proyecto de arquitectura y vela por su correcta materialización."],
["Calculista","Roles de obra","Ingeniero que dimensiona y verifica la estructura resistente de un proyecto."],
["Capataz","Roles de obra","Trabajador que supervisa directamente a una cuadrilla y coordina las tareas diarias en terreno."],
["Carpintero","Roles de obra","Oficial especializado en trabajos de madera, moldajes o estructuras de tabiquería."],
["Constructor civil","Roles de obra","Profesional a cargo de dirigir y ejecutar técnicamente una obra de construcción."],
["Electricista","Roles de obra","Oficial especializado en instalar y mantener sistemas eléctricos de una edificación."],
["Enfierrador","Roles de obra","Oficial especializado en armar y colocar la enfierradura antes del vaciado de hormigón."],
["Gásfiter","Roles de obra","Oficial especializado en instalaciones sanitarias de agua y gas."],
["Ingeniero civil","Roles de obra","Profesional a cargo del diseño estructural y de infraestructura de un proyecto."],
["ITO","Roles de obra","Inspector Técnico de Obra; profesional que supervisa en representación del mandante el cumplimiento del proyecto y la normativa."],
["Jefe de obra","Roles de obra","Profesional o técnico a cargo de la ejecución diaria de la obra en terreno."],
["Jornal","Roles de obra","Trabajador contratado por día para labores generales de obra, o el pago correspondiente a esa jornada."],
["Maestro carpintero","Roles de obra","Oficial con mayor experiencia en el oficio de carpintería, encargado de las tareas más complejas."],
["Operador de maquinaria","Roles de obra","Trabajador capacitado para manejar excavadoras, grúas u otro equipo pesado en obra."],
["Pintor","Roles de obra","Oficial especializado en la aplicación de pinturas y revestimientos de terminación."],
["Prevencionista de riesgos","Roles de obra","Profesional encargado de identificar, controlar y prevenir riesgos de accidentes en la obra."],
["Residente de obra","Roles de obra","Profesional que representa al contratista en terreno durante toda la ejecución de la obra."],
["Soldador","Roles de obra","Oficial especializado en unir piezas metálicas mediante procesos de soldadura."],
["Topógrafo","Roles de obra","Profesional o técnico encargado de medir y trazar el terreno y los niveles de la obra."],
["AutoCAD","Software y herramientas digitales","Software de dibujo técnico asistido por computador, usado para planos de arquitectura e ingeniería."],
["BIM","Software y herramientas digitales","Building Information Modeling; metodología de modelado digital colaborativo de un proyecto de construcción, que en la práctica se aplica usando software como Revit, Tekla o ArchiCAD."],
["Libro de obra","Software y herramientas digitales","Registro oficial (físico o digital) donde se anotan instrucciones, observaciones y avances de la obra."],
["Planilla de autocontrol","Software y herramientas digitales","Formulario que usa el propio ejecutor de una partida para verificar y respaldar que cumplió las especificaciones antes de la inspección."],
["Presto","Software y herramientas digitales","Software especializado en presupuestos, programación y control de obras de construcción."],
["Revit","Software y herramientas digitales","Software de modelado BIM usado para proyectar arquitectura, estructura e instalaciones de forma integrada; es una de las herramientas más usadas en el mundo para trabajar bajo la metodología BIM."],
["Nivel de ingeniero","Herramientas","Instrumento óptico topográfico que mide diferencias de altura entre puntos mediante una mira y visuales horizontales."],
["Estación total","Herramientas","Instrumento topográfico electrónico que mide ángulos y distancias para determinar coordenadas de puntos en terreno."],
["Mira topográfica","Herramientas","Regla graduada que se lee a través del nivel de ingeniero para determinar diferencias de altura."],
["GPS geodésico","Herramientas","Equipo satelital de alta precisión usado para georreferenciar puntos en levantamientos topográficos."],
["Geomensura","Geotecnia y topografía","Disciplina que mide, representa y delimita el terreno, base para el trazado y la propiedad de un predio."],
["Ingeniero geomensor","Roles de obra","Profesional a cargo de la medición, deslinde y representación gráfica de terrenos y predios."],
["Ingeniero constructor","Roles de obra","Título profesional equivalente al de constructor civil, otorgado por algunas universidades e institutos."],
["Ingeniero civil en obras civiles","Roles de obra","Título profesional orientado al diseño y ejecución de infraestructura y edificación, con formación similar al ingeniero civil."],
["Mecánica de suelos","Geotecnia y topografía","Rama de la ingeniería que estudia el comportamiento del suelo para diseñar fundaciones y obras de tierra."],
["Estudio de suelo","Geotecnia y topografía","Informe técnico que caracteriza el terreno y entrega recomendaciones de fundación para un proyecto."],
["Capacidad de soporte","Geotecnia y topografía","Máxima carga que un suelo puede resistir sin fallar ni deformarse excesivamente."],
["Movimiento de tierras","Geotecnia y topografía","Conjunto de faenas de corte, relleno y transporte de suelo necesarias para adecuar el terreno a un proyecto."],
["Compactación de suelo","Geotecnia y topografía","Proceso que densifica el suelo reduciendo sus vacíos, aumentando su capacidad de soporte."],
["Sondaje geotécnico","Geotecnia y topografía","Perforación exploratoria que permite conocer la estratigrafía y propiedades del suelo en profundidad."],
["Nivel freático","Geotecnia y topografía","Profundidad a la que se encuentra el agua subterránea en un terreno, relevante para fundaciones y excavaciones."],
["Niveleta","Medidas y trazado","Estructura provisoria de madera clavada en terreno, usada como referencia para el trazado y los niveles de una obra."],
["Betonera","Maquinaria","Máquina que mezcla cemento, agua, arena y áridos para producir hormigón u mortero; sinónimo de hormigonera o mezcladora."],
["Áridos","Materiales","Materiales granulares como arena y grava que, junto al cemento y agua, forman el hormigón o mortero."],
["Fierro","Materiales","Nombre coloquial que se da en obra al acero de refuerzo o enfierradura."],
["EPS","Materiales","Poliestireno expandido; material aislante térmico liviano usado en muros, techos y radieres."],
["PPR","Materiales","Polipropileno random; tipo de tubería plástica resistente al calor usada en instalaciones sanitarias de agua caliente."],
["PVC","Materiales","Policloruro de vinilo; material plástico usado en tuberías de agua potable, alcantarillado y aguas lluvia."],
["Cubicación","Faena y obra","Cálculo de la cantidad de materiales u obra necesaria a partir de las mediciones de un proyecto."],
["OSB","Materiales","Tablero de virutas de madera orientadas y prensadas, usado en tabiques, cielos y moldajes."],
["Terciado","Materiales","Tablero de láminas de madera encoladas, usado en moldajes, revestimientos y mobiliario de obra."],
["Clavo","Materiales","Elemento metálico puntiagudo usado para unir piezas de madera u otros materiales."],
["Tornillo autoperforante","Materiales","Tornillo que perfora y fija sin necesidad de perno previo, usado en estructuras metálicas livianas."],
["Perno de expansión","Materiales","Anclaje mecánico que se fija a presión dentro de un elemento de hormigón u obra terminada."],
["Cerámica","Terminaciones","Revestimiento de piso o muro fabricado en base a arcilla cocida y esmaltada."],
["Porcelanato","Terminaciones","Revestimiento cerámico de alta densidad y baja porosidad, usado en pisos y muros."],
["Pintura látex","Materiales","Pintura al agua usada principalmente en muros interiores y exteriores."],
["Pintura esmalte","Materiales","Pintura de mayor resistencia y brillo, usada en madera, metal y superficies de mayor exposición."],
["Impermeabilizante líquido","Materiales","Producto aplicado en estado líquido que forma una membrana impermeable al secar."],
["Malla rachel","Materiales","Malla plástica tejida usada como cierre perimetral o protección en faenas de obra."],
["Cinta de señalización","Seguridad","Cinta usada para delimitar zonas de riesgo o restringir el acceso en obra."],
["Casco de seguridad","Seguridad","Elemento de protección personal que resguarda la cabeza de golpes o caída de objetos."],
["Arnés de seguridad","Seguridad","Equipo que sujeta al trabajador para prevenir caídas al trabajar en altura."],
["Chaleco reflectante","Seguridad","Prenda de alta visibilidad usada para identificar a los trabajadores en obra."],
["ODI","Seguridad","Obligación de Informar; charla en que el empleador informa a el trabajador los riesgos de su labor."],
["Charla de seguridad","Seguridad","Instancia breve y diaria en que se repasan los riesgos y medidas de prevención de la faena."],
["Trabajo en altura","Seguridad","Actividad realizada sobre 1,8 metros de altura, que exige medidas específicas de protección contra caídas."],
["Camión mixer","Maquinaria","Camión con tambor giratorio que transporta y mantiene homogéneo el hormigón hasta la obra."],
["Camión tolva","Maquinaria","Vehículo usado para transportar áridos, tierra o escombros."],
["Grúa horquilla","Maquinaria","Máquina usada para levantar y trasladar materiales paletizados dentro de la obra."],
["Winche","Maquinaria","Equipo mecánico que eleva o traslada cargas mediante un cable enrollado en un tambor."],
["Vibropisón","Maquinaria","Equipo de compactación manual usado en zanjas y superficies reducidas."],
["Zona sísmica","Geotecnia y topografía","Clasificación del territorio según su nivel de peligro sísmico, definida en la norma NCh433."],
["Especificaciones técnicas (EETT)","Normativa e instituciones","Documento que detalla materiales, calidades y procedimientos exigidos para la ejecución de un proyecto."],
["KPI","Faena y obra","Key Performance Indicator; indicador que mide el desempeño de una obra en plazo, costo, calidad o seguridad."],
["AP","Instalaciones","Agua potable; red de tuberías que abastece de agua apta para consumo a una edificación."],
["AS","Instalaciones","Aguas servidas; red de tuberías que evacua las aguas residuales de una edificación hacia el alcantarillado."],
["Plastificante","Materiales","Aditivo que mejora la trabajabilidad del hormigón o mortero sin aumentar la cantidad de agua."],
["Superplastificante","Materiales","Aditivo de alta eficiencia que aumenta fuertemente la fluidez del hormigón manteniendo baja la razón agua-cemento."],
["Acelerante","Materiales","Aditivo que reduce el tiempo de fraguado y acelera el desarrollo de resistencia del hormigón."],
["Retardante","Materiales","Aditivo que prolonga el tiempo de fraguado del hormigón, útil en climas cálidos o vaciados extensos."],
["Edificación","Tipos de obra","Construcción destinada a albergar personas o actividades, como viviendas, oficinas o equipamiento."],
["Obra vial","Tipos de obra","Infraestructura destinada al tránsito vehicular, como caminos, puentes o autopistas."],
["Obra sanitaria","Tipos de obra","Infraestructura destinada a la captación, tratamiento o distribución de agua potable y alcantarillado."],
["Obra hidráulica","Tipos de obra","Infraestructura destinada al manejo del agua, como embalses, canales o defensas fluviales."],
["Vivienda social","Tipos de obra","Edificación habitacional destinada a familias de menores recursos, generalmente con subsidio estatal."],
["Edificación en altura","Tipos de obra","Construcción de varios pisos, típicamente con estructura de hormigón armado u acero."],
["Ampliación","Tipos de obra","Obra que aumenta la superficie construida de una edificación existente."],
["Remodelación","Tipos de obra","Obra que modifica la distribución o terminaciones de una edificación existente sin ampliarla."],
["Carretilla dosificadora","Herramientas","Carretilla que adecua su capacidad de carga para dosificar la proporción de áridos y cemento en el hormigón."],
["Chequeo","Faena y obra","Control realizado para asegurar la buena ejecución de una faena."],
["Chuzo","Herramientas","Barra de hierro puntiaguda de al menos 1,5 m usada para abrir suelos o romper pavimentos."],
["Clavo Hilti","Materiales","Clavo que se dispara desde una pistola especial mediante un fulminante, usado para fijar sobre hormigón o acero."],
["Clavo líquido","Materiales","Pegamento químico que une piezas de madera en toda su superficie de contacto, reemplazando al clavo tradicional."],
["Combo","Herramientas","Mazo metálico usado en distintas faenas de la construcción para hincar elementos al terreno."],
["Corte","Medidas y trazado","Sección realizada sobre un elemento o terreno para representar su geometría interna; en estructuras, también nombra al esfuerzo que tiende a deslizar una sección respecto de otra (ver Cizalle)."],
["Cuartón","Materiales","Pieza de madera escuadrada de 4 x 4 pulgadas."],
["Demarcar","Medidas y trazado","Delimitar un área de trabajo en la construcción."],
["Desaplome","Estructura","Condición de un elemento constructivo que perdió la verticalidad exigida."],
["Desmoldar","Faena y obra","Retirar los moldajes de una faena de hormigonado una vez que el hormigón ha fraguado."],
["Diablo","Herramientas","Herramienta de uso múltiple que sirve para desclavar, apalancar, golpear y destrabar."],
["Eje","Medidas y trazado","Línea que divide un sector o elemento en dos partes iguales, usada como referencia de trazado."],
["Emplazar","Medidas y trazado","Trazar la ubicación exacta de una construcción en el terreno."],
["Encastillar","Faena y obra","Disponer piezas de madera en forma predeterminada para su secado o almacenamiento."],
["Envigado","Estructura","Conjunto de vigas soportantes de una construcción."],
["Ensamblar","Faena y obra","Unir dos o más piezas mediante sistemas de ensamble adecuados."],
["Escarpe","Fundaciones","Desbaste de un terreno para emparejarlo, eliminando resaltes y tierra vegetal no apta para construir."],
["Escuadría","Materiales","Expresión numérica de las dimensiones de la sección transversal de una pieza de madera."],
["Espárrago","Materiales","Barra de fierro empotrada en hormigón que sirve para anclar una estructura de madera a su fundación."],
["Estanqueidad","Terminaciones","Capacidad de un elemento o sistema de impedir el paso de agua, aire u otro fluido."],
["Fachada","Estructura","Paramento exterior, generalmente principal, de un edificio."],
["Fieltro","Materiales","Lámina impermeable, generalmente bituminosa, usada para proteger estructuras de la humedad."],
["Formón","Herramientas","Herramienta metálica de carpintería usada para desbastar u horadar piezas de madera."],
["Gramil","Herramientas","Instrumento de carpintería usado para trazar líneas paralelas al canto de una pieza de madera."],
["Gravilla","Materiales","Grava de tamaño pequeño usada en pavimentos u hormigones de ornato."],
["Hilada","Estructura","Línea horizontal completa de ladrillos o bloques en un muro de albañilería."],
["Ignífugo","Materiales","Material resistente al fuego."],
["Industrializado","Tipos de obra","Sistema constructivo en que las partes de una vivienda se fabrican de antemano y se ensamblan en un recinto industrial."],
["Lienza","Herramientas","Cordón de hilo usado para el trazado y el aplome en una construcción."],
["Línea de edificación","Normativa e instituciones","Línea que determina la Dirección de Obras Municipales para ubicar una construcción respecto de la calle."],
["Llana","Herramientas","Herramienta que permite alisar los estucos aplicados sobre un muro o pavimento."],
["Módulo","Diseño","Elemento o conjunto de elementos que se repite en una construcción para hacerla más fácil, regular y económica."],
["Muro portante","Estructura","Muro que soporta estructuralmente una parte importante de la construcción."],
["N.P.T.","Medidas y trazado","Nivel de Piso Terminado; punto de referencia para alinear los distintos pavimentos de una construcción."],
["Ortogonalidad","Diseño","Condición de un diseño resuelto con ángulos rectos."],
["Pandeo","Estructura","Deformación de una pieza esbelta, encorvándose bajo compresión, habitualmente en su punto central."],
["Pendiente","Estructura","Inclinación de una techumbre que permite el escurrimiento de aguas, o inclinación de un terreno."],
["Perímetro","Medidas y trazado","Contorno de una construcción o de un terreno."],
["Picota","Herramientas","Herramienta de fierro usada para picar o romper materiales en obra."],
["Pisón","Herramientas","Instrumento pesado con forma de cono truncado usado para apretar tierra o piedras manualmente."],
["Pletina metálica","Materiales","Pieza metálica plana usada en uniones y refuerzos estructurales."],
["Polín","Materiales","Trozo de madera de sección cilíndrica."],
["Premezclado","Materiales","Elemento constructivo que llega a obra con un proceso de mezclado previo, como el hormigón premezclado."],
["Pretrazado","Medidas y trazado","Trazado provisorio y no exacto que delimita el área donde se realizará la construcción."],
["Puntal","Estructura","Pieza fuertemente hincada en el terreno que sostiene una pared desaplomada o una edificación en riesgo de desplome."],
["Rasgo","Estructura","Vano o abertura de un muro o tabique."],
["Rebaje","Medidas y trazado","Disminución del nivel o superficie horizontal de un terreno."],
["Recinto","Diseño","Espacio comprendido dentro de ciertos límites dentro de una edificación."],
["Replantear","Medidas y trazado","Trazar en el terreno la planta de una obra ya estudiada y proyectada, revisando sus medidas."],
["Riostra","Estructura","Pieza dispuesta diagonalmente sobre una estructura que asegura la invariabilidad de su forma."],
["Sello de fundación","Fundaciones","Superficie de término de las fundaciones, donde estas se apoyan sobre el terreno de soporte."],
["Sello de excavación","Fundaciones","Superficie de término de una excavación, libre de materiales orgánicos."],
["Sobresolera","Estructura","Pieza de madera traslapada con la solera superior de un panel, que amarra y une estructuralmente los paneles."],
["Taquímetro","Herramientas","Instrumento óptico que mide simultáneamente distancias y ángulos horizontales y verticales, similar al teodolito."],
["Tecle","Maquinaria","Elevador de carga estático o móvil que funciona mecánica o eléctricamente."],
["Tirafondo","Materiales","Tornillo grande de cabeza especial usado para afianzar piezas de madera entre sí."],
["Tizador","Herramientas","Instrumento con polvo de tiza y una lienza que, al impregnarse, demarca líneas rectas de referencia."],
["Tolerancia","Normativa e instituciones","Margen o diferencia permitida en la cantidad y calidad de una obra respecto de lo contratado."],
["Torcedura","Materiales","Alabeo helicoidal en el sentido longitudinal y transversal de las fibras de una pieza de madera."],
["Traslapo","Faena y obra","Superposición parcial de un elemento sobre otro, como en tejas de un tejado o barras de refuerzo."],
["Tekla","Software y herramientas digitales","Software BIM especializado en modelado y detallamiento de estructuras de acero y hormigón."],
["SketchUp","Software y herramientas digitales","Software de modelado 3D intuitivo, usado para bocetar volúmenes arquitectónicos y presentaciones rápidas."],
["Navisworks","Software y herramientas digitales","Software que integra modelos BIM de distintas disciplinas para revisar interferencias y coordinar proyectos."],
["Napa freática","Geotecnia y topografía","Capa de agua subterránea contenida en el suelo o roca permeable, cuyo nivel superior se conoce como nivel freático."],
["Acuífero","Geotecnia y topografía","Formación geológica permeable capaz de almacenar y transmitir agua subterránea en cantidad aprovechable."],
["Permeabilidad del suelo","Geotecnia y topografía","Capacidad de un suelo para permitir el paso de agua a través de sus poros o fisuras."],
["Capilaridad","Geotecnia y topografía","Fenómeno por el cual el agua asciende por los poros de un material, como el hormigón o la albañilería, sin presión externa."],
["Dren","Instalaciones","Elemento o sistema que capta y evacua el agua infiltrada en el suelo alrededor de una fundación."],
["Subdrenaje","Fundaciones","Sistema de drenes instalado bajo el nivel del terreno para controlar el agua subterránea antes de que afecte la fundación."],
["Capa freática colgada","Geotecnia y topografía","Acumulación local y temporal de agua subterránea sobre un estrato poco permeable, distinta de la napa freática general."],
["Ley 21.305","Normativa e instituciones","Ley de Eficiencia Energética; exige calificación o precalificación energética obligatoria para la recepción final de ciertas edificaciones en Chile."],
["Calificación energética","Normativa e instituciones","Evaluación oficial que informa el consumo energético de una vivienda o edificio mediante una etiqueta de la A+ a la G."],
["Precalificación energética","Normativa e instituciones","Evaluación del desempeño energético de un proyecto en etapa de diseño, previa a la construcción."],
["Etiquetado energético","Normativa e instituciones","Sistema que clasifica el desempeño energético de una edificación en una escala de letras, de la A+ a la G."],
["Reglamentación térmica (NCh 853)","Normativa e instituciones","Normativa chilena que establece los requisitos térmicos que deben cumplir las viviendas, incluyendo transmitancia térmica, condensación y ventilación mínima."],
["Zonificación climático-habitacional (NCh1079)","Normativa e instituciones","Norma que divide el territorio chileno en zonas climáticas para efectos de exigencias de aislación térmica en viviendas."],
["Presa","Tipos de obra","Estructura construida para retener agua en un cauce, formando un embalse con fines de riego, agua potable o generación eléctrica."],
["Embalse","Tipos de obra","Depósito de agua que se forma al retener el curso de un río mediante una presa."],
["Canal de riego","Tipos de obra","Conducto artificial abierto que transporta agua desde una fuente hasta terrenos agrícolas."],
["Acueducto","Tipos de obra","Estructura que transporta agua a distancia, ya sea de forma subterránea, superficial o elevada."],
["Planta de tratamiento de agua potable","Tipos de obra","Instalación donde se potabiliza agua cruda mediante procesos físicos y químicos antes de distribuirla a la red."],
["Obra portuaria","Tipos de obra","Infraestructura destinada a la carga, descarga y atraque de embarcaciones, como muelles y terminales marítimos."],
["Aeropuerto","Tipos de obra","Infraestructura destinada al despegue, aterrizaje y operación de aeronaves, con pistas, torres y terminales."],
["Puerto","Tipos de obra","Instalación costera o fluvial que permite el atraque de naves para el transporte de carga o pasajeros."],
["Carretera","Tipos de obra","Vía pública destinada al tránsito de vehículos, generalmente de mayor capacidad y velocidad que un camino local."],
["Túnel","Tipos de obra","Obra subterránea que permite el paso de personas, vehículos o instalaciones a través de un macizo de tierra o roca."],
["Puente","Tipos de obra","Estructura que permite salvar un obstáculo, como un río o una quebrada, conectando dos puntos de una vía."],
["Sismo interplaca","Geotecnia y topografía","Terremoto originado por la fricción y liberación de energía entre dos placas tectónicas en su zona de contacto."],
["Sismo intraplaca","Geotecnia y topografía","Terremoto producido por rupturas internas dentro de una misma placa tectónica, lejos de su borde de contacto."],
["Sismo cortical","Geotecnia y topografía","Terremoto originado por fallas superficiales dentro de la corteza terrestre, generalmente de menor profundidad."],
["Sismo volcánico","Geotecnia y topografía","Terremoto causado por el movimiento de magma o gases dentro de un sistema volcánico activo."],
["Flexión","Estructura","Esfuerzo que provoca que un elemento se curve, generando tracción en una cara y compresión en la opuesta."],
["Compresión","Estructura","Esfuerzo que tiende a acortar o aplastar un elemento por la acción de cargas que actúan en sentidos opuestos hacia su interior."],
["Flexotracción","Estructura","Combinación de flexión y tracción que actúa simultáneamente sobre un elemento, relevante en el ensayo de resistencia de vigas de hormigón."],
["Cizalle","Estructura","Esfuerzo que tiende a hacer deslizar una sección de un elemento respecto de la sección adyacente; sinónimo técnico de corte."],
["Cemento","Materiales","Material aglomerante en polvo que, mezclado con agua, reacciona químicamente y endurece, dando origen al hormigón y al mortero."],
["Arquitectura","Diseño","Disciplina que proyecta y da forma a los espacios habitables, integrando función, estética y factibilidad constructiva."],
["Croquis","Diseño","Dibujo a mano alzada usado para representar rápidamente una idea de diseño o un detalle constructivo."],
["Granulometría","Geotecnia y topografía","Distribución del tamaño de las partículas de un suelo o árido, determinada mediante tamizado."],
["Límite de Atterberg","Geotecnia y topografía","Conjunto de ensayos que definen los límites de humedad entre los distintos estados de consistencia de un suelo fino (líquido, plástico y sólido)."],
["Límite líquido","Geotecnia y topografía","Contenido de humedad a partir del cual un suelo fino pasa de un estado plástico a un estado líquido."],
["Límite plástico","Geotecnia y topografía","Contenido de humedad a partir del cual un suelo fino pasa de un estado semisólido a un estado plástico."],
["Plasticidad","Geotecnia y topografía","Capacidad de un suelo de deformarse sin romperse dentro de un rango de humedad determinado."],
["Consolidación","Geotecnia y topografía","Proceso de reducción de volumen de un suelo saturado por la expulsión gradual del agua contenida en sus poros bajo carga."],
["Límite de fluencia","Estructura","Esfuerzo a partir del cual un material, como el acero, comienza a deformarse permanentemente sin aumento proporcional de carga."],
["Límite elástico","Estructura","Máximo esfuerzo que puede soportar un material recuperando su forma original al retirar la carga."],
["PRI","Normativa e instituciones","Plano Regulador Intercomunal; instrumento que planifica el uso de suelo entre varias comunas de un mismo territorio."],
["Coeficiente de constructibilidad","Normativa e instituciones","Factor que, multiplicado por la superficie del terreno, define los metros cuadrados totales máximos que se pueden edificar en él."],
["Coeficiente de ocupación de suelo","Normativa e instituciones","Porcentaje máximo del terreno que puede ocupar la construcción en su primer piso."],
["Antejardín","Normativa e instituciones","Distancia mínima obligatoria, exigida por el plan regulador, entre la línea oficial y la edificación."],
["Adosamiento","Normativa e instituciones","Construcción que se levanta pegada al límite del predio vecino, bajo las condiciones que autoriza la normativa."],
["Densidad","Normativa e instituciones","Cantidad máxima de habitantes o viviendas permitidas por hectárea en un terreno, según la norma urbanística."],
["Superficie edificada","Normativa e instituciones","Total de metros cuadrados construidos en todos los pisos de una edificación."],
["Altura de edificación","Normativa e instituciones","Medida máxima permitida, en metros o pisos, para la construcción en un predio según la normativa vigente."],
["Bien Nacional de Uso Público (BNUP)","Normativa e instituciones","Espacio destinado al libre tránsito de la comunidad, como calles, aceras y plazas."],
["Loteo","Normativa e instituciones","División de un terreno que, por ley, incluye la apertura de nuevas calles públicas."],
["Subdivisión predial","Normativa e instituciones","División de un terreno en lotes más pequeños que no requiere la apertura de nuevas vías públicas."],
["Fusión predial","Normativa e instituciones","Unión legal de dos o más terrenos bajo un solo rol de propiedad."],
["Cambio de destino","Normativa e instituciones","Trámite municipal que modifica el uso aprobado de un inmueble, por ejemplo de vivienda a oficina."],
["Línea oficial","Normativa e instituciones","Límite legal entre la propiedad privada y el espacio público, como una calle o vereda."],
["Deslinde","Normativa e instituciones","Límite perimetral o frontera legal entre dos propiedades privadas."],
["Distanciamiento","Normativa e instituciones","Distancia mínima obligatoria que debe existir entre una ventana o muro y el predio vecino."],
["Ochavo","Normativa e instituciones","Recorte obligatorio en la esquina de una edificación, exigido para mejorar la visibilidad en el cruce vial."],
["Uso de suelo","Normativa e instituciones","Tipo de actividad permitida en una zona específica del territorio, como residencial, comercial o industrial."],
["Expropiación","Normativa e instituciones","Compra forzosa de un terreno privado por parte del Estado, generalmente para ejecutar obras públicas."],
["Servidumbre de paso","Normativa e instituciones","Derecho legal que permite transitar por un terreno ajeno para acceder a otra propiedad."],
["Fachada continua","Normativa e instituciones","Configuración urbana en que los edificios se levantan pegados entre sí, sin distanciamiento lateral."],
["Carga de ocupación","Normativa e instituciones","Cantidad máxima de personas que legalmente pueden habitar o usar un espacio de forma simultánea."],
["Vía de evacuación","Seguridad","Camino continuo, seguro y libre de obstáculos que permite salir de un edificio en caso de emergencia."],
["Obra nueva","Tipos de obra","Proyecto de edificación que se levanta desde cero en un terreno vacío."],
["Alteración","Normativa e instituciones","Modificación interior de un edificio que no cambia su superficie total edificada."],
["Suelo urbano","Normativa e instituciones","Territorio destinado a asentamientos humanos según las normas del plan regulador."],
["Suelo rural","Normativa e instituciones","Terreno ubicado fuera del límite urbano, reservado generalmente a usos agrícolas."],
["Límite urbano","Normativa e instituciones","Línea del plan regulador que separa el área urbana de una comuna del área rural."],
["Parcelación","Normativa e instituciones","División de un terreno rural en lotes individuales, comúnmente de superficie mínima de 5.000 m²."],
["Patrimonio histórico","Normativa e instituciones","Inmueble o zona protegida legalmente por su valor cultural o arquitectónico, con restricciones especiales de intervención."],
["Cierre perimetral","Terminaciones","Muro, reja o cerco definitivo que delimita una propiedad respecto del exterior."],
["Demolición","Faena y obra","Proceso autorizado por la Dirección de Obras Municipales para derribar parcial o totalmente una estructura."],
["Aviso de inicio de obra","Normativa e instituciones","Notificación formal que se entrega a la municipalidad antes de comenzar la construcción."],
["Ley del Mono","Normativa e instituciones","Nombre coloquial de las leyes que han permitido la regularización simplificada de viviendas construidas sin permiso."],
["D.F.L. 2","Normativa e instituciones","Decreto con Fuerza de Ley que otorga beneficios tributarios a viviendas económicas de hasta 140 m² edificados."],
["Contratista","Roles de obra","Empresa o persona que se compromete a ejecutar una obra para el mandante, según lo estipulado en un contrato."],
["Subcontratista","Roles de obra","Empresa que ejecuta una parte específica de la obra por encargo del contratista principal."],
["Presupuesto de obra","Faena y obra","Documento que detalla y valoriza todas las partidas necesarias para ejecutar un proyecto de construcción."],
["Estado de pago","Faena y obra","Documento periódico que respalda el avance de obra ejecutado, usado para solicitar el pago correspondiente al contratista."],
["Carta Gantt","Faena y obra","Herramienta gráfica que programa en el tiempo las actividades de una obra y su duración estimada."],
["Muro perimetral","Estructura","Muro que delimita el borde de una edificación o de un terreno."],
["Albañilería confinada","Estructura","Sistema de albañilería reforzado con elementos de hormigón armado (cadenas y pilares) que la enmarcan en todo su perímetro."],
["Albañilería armada","Estructura","Sistema de albañilería reforzado con barras de acero introducidas en sus huecos y rellenas con mortero u hormigón."],
["Ladrillo fiscal","Materiales","Ladrillo de arcilla cocida con huecos, de dimensiones estandarizadas, ampliamente usado en albañilería en Chile."],
["Ladrillo princesa","Materiales","Ladrillo cerámico de menor espesor que el fiscal, usado principalmente en tabiques divisorios no estructurales."],
["Tijeral","Estructura","Estructura triangulada de madera que sostiene la cubierta de un techo, equivalente a la cercha en construcción en madera."],
["Costanera","Estructura","Perfil metálico liviano en forma de C o Z que se apoya sobre la cercha o tijeral para sostener la cubierta."],
["Internit","Materiales","Nombre comercial genericizado de una plancha de fibrocemento usada como revestimiento exterior o de cubierta."],
["Metalcón","Estructura","Sistema constructivo de perfiles de acero galvanizado liviano, usado como alternativa a la madera en tabiques y entrepisos."],
["Socalzadura","Fundaciones","Técnica que refuerza o profundiza una fundación existente sin interrumpir el funcionamiento de la estructura que soporta."],
["Enjarrado","Terminaciones","Primera capa de mortero aplicada sobre un muro para emparejar su superficie antes del estuco fino."],
["Arena","Materiales","Árido fino que, junto al cemento y el agua, forma parte del mortero y el hormigón."],
["Puente de adherencia","Materiales","Producto o tratamiento que mejora la unión entre una superficie de hormigón antigua y una nueva capa que se aplica sobre ella."],
["Asentamiento de cono (Abrams)","Faena y obra","Ensayo que mide la consistencia y trabajabilidad del hormigón fresco mediante un cono metálico estandarizado."],
["Probeta","Faena y obra","Muestra cilíndrica de hormigón fresco que, una vez endurecida, se ensaya a compresión para verificar su resistencia."],
["Piso flotante","Terminaciones","Revestimiento de piso que se instala sobre una base sin adherirse a ella, generalmente con sistema de encaje."],
["Vinílico","Terminaciones","Revestimiento de piso flexible fabricado en base a PVC, usado como alternativa económica a otros pavimentos."],
["Quicio","Terminaciones","Parte inferior del marco de una puerta, sobre la cual gira o se apoya la hoja."],
["Ventana termopanel","Terminaciones","Ventana compuesta por dos vidrios separados por una cámara de aire, que mejora la aislación térmica y acústica."],
["Imprimante","Materiales","Producto de base que se aplica antes de la pintura final para mejorar su adherencia y uniformidad."],
["Pasta muro","Materiales","Masilla que se aplica para emparejar imperfecciones de un muro antes de pintarlo."],
["Moldura","Terminaciones","Perfil decorativo que remata la unión entre distintos elementos, como muros, cielos o marcos."],
["Quincallería","Terminaciones","Conjunto de herrajes y accesorios metálicos usados en puertas, ventanas y muebles de obra."],
["WC","Instalaciones","Water closet; nombre habitual del artefacto sanitario destinado a la evacuación de desechos humanos."],
["Flexible (conexión)","Instalaciones","Tramo corto y flexible de tubería que conecta un artefacto sanitario a la red fija de agua."],
["Tubería de cobre","Instalaciones","Tubería metálica usada tradicionalmente en instalaciones de agua potable por su resistencia a la corrosión."],
["Gasfitería","Roles de obra","Oficio y especialidad dedicada a instalar y reparar redes de agua, gas y artefactos sanitarios."],
["Alcantarillado","Instalaciones","Red de tuberías destinada a evacuar las aguas servidas de una edificación hacia la red pública."],
["Cámara de inspección","Instalaciones","Estructura subterránea que permite acceder y revisar una red de alcantarillado o aguas lluvia."],
["Tablero eléctrico","Instalaciones","Gabinete donde se distribuyen y protegen los circuitos eléctricos de una edificación."],
["Diferencial","Instalaciones","Dispositivo de protección eléctrica que corta el suministro al detectar una fuga de corriente hacia tierra."],
["Calefón","Instalaciones","Artefacto a gas que calienta agua de forma instantánea para su uso sanitario."],
["Termo","Instalaciones","Artefacto que calienta y acumula agua para su uso sanitario posterior."],
["Fosa séptica","Instalaciones","Sistema de tratamiento de aguas servidas usado en lugares sin acceso a la red de alcantarillado pública."],
["Grifería","Instalaciones","Conjunto de llaves y artefactos que controlan el paso de agua en un punto de la red sanitaria."],
["Mástique","Materiales","Pasta selladora usada para rellenar juntas y evitar filtraciones de agua o aire."],
["Yesero","Roles de obra","Oficial especializado en la aplicación de yeso y estuco fino en muros y cielos."],
["Cargador frontal","Maquinaria","Máquina con una gran cuchara delantera usada para cargar, mover y apilar material a granel."],
["Minicargador","Maquinaria","Máquina compacta de carga frontal, muy maniobrable, usada en espacios reducidos de la obra."],
["Línea de vida","Seguridad","Sistema de cable o cuerda fija al que se conecta el arnés de un trabajador para prevenir caídas en altura."],
["Zapatos de seguridad","Seguridad","Calzado con puntera reforzada que protege los pies del trabajador ante impactos o aplastamiento."],
["Antiparras","Seguridad","Lentes de protección personal que resguardan los ojos de partículas, chispas o proyecciones."],
["Comité paritario","Seguridad","Organismo formado por representantes de la empresa y los trabajadores, encargado de la prevención de riesgos en la obra."],
["Baño químico","Faena y obra","Instalación sanitaria portátil usada temporalmente en obra mientras no existe una red de alcantarillado disponible."],
["Escombro","Faena y obra","Residuo o desecho sólido generado durante la construcción o demolición de una obra."],
["Botadero","Faena y obra","Lugar autorizado para depositar los escombros y residuos generados en una obra."],
["Amoladora","Herramientas","Herramienta eléctrica que, mediante un disco giratorio, corta o desbasta materiales como metal, hormigón o piedra."],
["Sierra circular","Herramientas","Herramienta eléctrica con disco dentado giratorio usada para cortar madera y otros materiales."],
["Vibrador de placa","Maquinaria","Equipo de compactación que se desplaza sobre una placa vibratoria, usado en suelos y bases de pavimento."],
["Allanadora","Maquinaria","Máquina giratoria que alisa y compacta la superficie del hormigón fresco en losas y radieres."],
["Regla vibradora","Herramientas","Herramienta que nivela y compacta la superficie del hormigón fresco mediante vibración, usada en pavimentos."],
["Alzaprima","Herramientas","Puntal o gato mecánico que sostiene temporalmente una estructura o elemento durante su construcción o reparación."],
["Cuchara de albañil","Herramientas","Herramienta plana con mango usada para aplicar y extender mortero en albañilería."],
["Licitación","Normativa e instituciones","Proceso mediante el cual se selecciona a un contratista para ejecutar una obra; puede ser pública (a través de organismos del Estado, como ChileCompra o el MOP) o privada (convocada directamente por un mandante particular)."],
["Escantillón","Herramientas","Regla o plantilla graduada que sirve para trazar y controlar repetidamente una misma medida en obra, como la altura de las hiladas de un muro de albañilería."],
["Solera inferior","Tabiquería - Elementos","Pieza horizontal de un tabique que se fija al piso o radier y recibe a los pies derechos."],
["Solera superior","Tabiquería - Elementos","Pieza horizontal ubicada en la parte superior de un tabique, sobre la que se apoya la techumbre o el entrepiso."],
["Transversal cortafuego","Tabiquería - Elementos","Pieza horizontal intermedia entre soleras, también llamada cadeneta, que rigidiza el tabique y retarda el paso del fuego entre pisos."],
["Jamba","Tabiquería - Elementos","Pieza vertical que enmarca un vano de puerta o ventana dentro de un tabique."],
["Dintel","Tabiquería - Elementos","Elemento horizontal que remata la parte superior de un vano de puerta o ventana, distribuyendo la carga a los pies derechos laterales."],
["Alféizar","Tabiquería - Elementos","Pieza horizontal que forma la base de un vano de ventana dentro de un tabique."],
["Puntal de dintel","Tabiquería - Elementos","Pieza vertical corta que transmite la carga desde la solera superior hasta el dintel de un vano."],
["Muchacho","Tabiquería - Elementos","Pieza vertical corta que se ubica bajo el alféizar, entre este y la solera inferior del tabique."],
["Recepción provisoria","Normativa e instituciones","Entrega preliminar de una obra entre el contratista y el mandante, previa a la recepción definitiva o municipal."],
["Recepción definitiva","Normativa e instituciones","Certificado final, otorgado por la Dirección de Obras Municipales, que autoriza habitar o usar un edificio ya terminado."],
["Pañolero","Roles de obra","Trabajador a cargo del pañol de obra, encargado de recibir, entregar y controlar herramientas y materiales."],
["Constructibilidad","Gestión y Administración de Obra","Grado en que el diseño de un proyecto facilita su ejecución eficiente en obra, considerando métodos constructivos, secuencias y recursos disponibles desde la etapa de diseño."],
["Oficina Técnica","Gestión y Administración de Obra","Área de una empresa constructora encargada de la gestión documental, cubicaciones, presupuestos y coordinación técnica de los proyectos en ejecución."],
["Construcción Industrializada","Tipos de obra","Método constructivo que traslada procesos tradicionalmente realizados en obra hacia una fábrica o planta, optimizando tiempos, calidad y control de producción."],
["Construcción Modular","Tipos de obra","Sistema constructivo basado en módulos prefabricados que se ensamblan en terreno, reduciendo plazos de ejecución respecto a la construcción tradicional."],
["Lean Construction","Gestión y Administración de Obra","Filosofía de gestión de proyectos que busca maximizar el valor y minimizar las pérdidas de tiempo, materiales y recursos durante todo el proceso constructivo."],
["Lean Management","Gestión y Administración de Obra","Enfoque de gestión orientado a la mejora continua y eliminación de actividades que no agregan valor, aplicado a la administración de proyectos de construcción."],
["LOD","Software y herramientas digitales","Level of Development: escala que define el grado de desarrollo y confiabilidad de la información contenida en un modelo BIM, desde su concepción esquemática hasta el detalle constructivo final."],
["Trazado y Replanteo","Medidas y trazado","Proceso de materializar en terreno las medidas y ubicaciones indicadas en los planos de proyecto, previo al inicio de la construcción."],
["Tolerancias","Medidas y trazado","Márgenes de variación aceptables entre las dimensiones proyectadas y las efectivamente construidas, definidos por la normativa o las especificaciones técnicas del proyecto."],
["Ruta Crítica","Gestión y Administración de Obra","Secuencia de actividades interdependientes de un proyecto que determina la duración mínima total de la obra; cualquier atraso en ellas retrasa el proyecto completo."],
["A.P.U.","Gestión y Administración de Obra","Análisis de Precios Unitarios: desglose detallado de los costos de materiales, mano de obra y equipos necesarios para ejecutar una unidad de una partida específica del presupuesto."],
["Sumidero","Instalaciones","Dispositivo de captación que recolecta aguas lluvias o de escorrentía superficial y las conduce hacia la red de drenaje."],
["Dren de Aguas Lluvias","Instalaciones","Sistema de tuberías o canalizaciones destinado a evacuar las aguas lluvias captadas desde techumbres, patios o vías hacia un punto de descarga."],
["Corrientes Débiles","Instalaciones","Conjunto de instalaciones eléctricas de baja intensidad, como redes de datos, telefonía, alarmas y CCTV, que se diferencian de las instalaciones de fuerza."],
["Paisajismo","Diseño","Disciplina orientada al diseño y tratamiento de espacios exteriores, integrando vegetación, mobiliario urbano y elementos naturales al proyecto."],
["Pavimentación","Pavimentos","Proceso de construcción de las capas superficiales, como base, subbase y carpeta, que conforman un pavimento vehicular o peatonal."],
["Áreas verdes","Diseño","Superficies destinadas a vegetación y esparcimiento dentro de un proyecto, reguladas habitualmente por normativa urbana y planes reguladores."],
["Caballete","Terminaciones","Elemento de cubierta que remata y protege la unión entre dos faldones de techo en su punto más alto o cumbrera."],
["Limatesa","Estructura","Línea de encuentro saliente entre dos faldones de una cubierta, típica de techos a cuatro aguas."],
["Limahoya","Estructura","Línea de encuentro entrante entre dos faldones de una cubierta, por donde escurren las aguas lluvias hacia el desagüe."],
["Destronque","Faena y obra","Faena de remoción de troncos y raíces del terreno, previa a los trabajos de movimiento de tierra o fundaciones."],
["Red de Fuerza (Enchufes)","Instalaciones","Instalación eléctrica destinada a alimentar equipos y artefactos de mayor consumo, diferenciada de la red de iluminación."],
["Base Administrativa","Gestión y Administración de Obra","Documento que establece las condiciones legales, comerciales y de procedimiento que regirán un proceso de licitación."],
["Calendario de Licitación","Gestión y Administración de Obra","Cronograma oficial que define las fechas y plazos de cada etapa de un proceso de licitación, desde la publicación hasta la adjudicación."],
["Boletas","Gestión y Administración de Obra","Documentos de garantía entregados por el contratista para asegurar el cumplimiento del contrato, la seriedad de la oferta o el correcto uso del anticipo."],
["Retenciones","Gestión y Administración de Obra","Porcentaje del pago retenido por el mandante durante la ejecución de la obra, como garantía frente a posibles defectos o incumplimientos."],
["Multas","Gestión y Administración de Obra","Sanciones económicas aplicadas al contratista por incumplimientos contractuales, como atrasos en el plazo de entrega."],
["Estados de Pago","Gestión y Administración de Obra","Documentos periódicos que respaldan el avance físico y financiero de una obra, utilizados para solicitar el pago correspondiente al mandante."],
["Planos","Diseño","Representación gráfica técnica de un proyecto, que detalla dimensiones, materiales y especificaciones necesarias para su ejecución."],
["Informe de Impacto Vial","Normativa e instituciones","Estudio técnico que evalúa los efectos de un proyecto sobre la circulación vehicular y peatonal del entorno, exigido por la autoridad competente."],
["Informe de Impacto Ambiental","Normativa e instituciones","Estudio que evalúa los efectos que un proyecto puede generar sobre el medioambiente, requerido para obtener las autorizaciones correspondientes."],
["Presupuesto Oficial","Gestión y Administración de Obra","Estimación de costos elaborada por el mandante como referencia para evaluar las ofertas presentadas en un proceso de licitación."],
["Propuesta Abierta","Gestión y Administración de Obra","Modalidad de licitación en la que cualquier contratista que cumpla los requisitos puede participar libremente."],
["Propuesta Cerrada","Gestión y Administración de Obra","Modalidad de licitación restringida a un grupo específico de contratistas previamente invitados o precalificados."],
["Licitación Pública","Gestión y Administración de Obra","Proceso de contratación regulado por la Ley de Compras Públicas N.° 19.886, abierto a cualquier oferente que cumpla los requisitos establecidos por un organismo del Estado."],
["Licitación Privada","Gestión y Administración de Obra","Proceso de contratación entre privados, sin sujeción a la normativa de compras públicas, cuyas condiciones son definidas libremente por el mandante."],
["Programación (Tiempos de Ejecución)","Gestión y Administración de Obra","Planificación que define la secuencia, duración y relación entre las actividades de un proyecto, habitualmente representada en una Carta Gantt."],
["Estudio de Propuestas","Gestión y Administración de Obra","Análisis técnico y económico de las ofertas recibidas en una licitación, previo a la decisión de adjudicación."],
["Homologación (Comparación o igualdad)","Gestión y Administración de Obra","Proceso de verificar que un material, producto o proveedor alternativo cumple con las mismas especificaciones y estándares del especificado originalmente."],
["Memorias de Cálculo","Estructura","Documento que respalda y justifica los cálculos estructurales, hidráulicos o eléctricos utilizados en el diseño de un proyecto."],
["Estribo","Estructura","Refuerzo transversal, generalmente de acero, que envuelve las barras longitudinales de una viga o columna para resistir esfuerzos de corte y confinar el hormigón."],
["Tendel","Estructura","Capa horizontal de mortero que une una hilada de ladrillos con la siguiente en un muro de albañilería."],
["Llaga","Estructura","Junta vertical de mortero entre dos ladrillos consecutivos de una misma hilada."],
["Cal hidratada","Materiales","Material aglomerante obtenido de la calcinación de piedra caliza, usado como componente de morteros y estucos por su plasticidad y retención de agua."],
["HDPE","Materiales","Polietileno de alta densidad; plástico usado en tuberías, geomembranas y ductos por su resistencia química y durabilidad."],
["LCA (Análisis de Ciclo de Vida)","Sustentabilidad y Medio Ambiente","Metodología que evalúa los impactos ambientales de un material o edificación a lo largo de todas sus etapas: extracción, fabricación, uso y disposición final."],
["Sustentabilidad","Sustentabilidad y Medio Ambiente","Capacidad de satisfacer las necesidades actuales sin comprometer los recursos disponibles para las futuras generaciones, con énfasis en el uso eficiente de los recursos."],
["Sostenibilidad","Sustentabilidad y Medio Ambiente","Concepto más amplio que busca el equilibrio entre lo ambiental, lo social y lo económico en un proyecto; a menudo usado como sinónimo de sustentabilidad en el uso cotidiano."],
["Huella de carbono","Sustentabilidad y Medio Ambiente","Medición de las emisiones de gases de efecto invernadero asociadas directa o indirectamente a un proyecto, material o proceso constructivo."],
["Economía circular en construcción","Sustentabilidad y Medio Ambiente","Enfoque que busca reducir, reutilizar y reciclar materiales de construcción a lo largo del ciclo de vida de una edificación, minimizando residuos."],
["LEED","Sustentabilidad y Medio Ambiente","Certificación internacional (Leadership in Energy and Environmental Design) que evalúa el desempeño ambiental de una edificación en categorías como energía, agua y materiales."],
["BREEAM","Sustentabilidad y Medio Ambiente","Certificación de sustentabilidad de origen británico (Building Research Establishment Environmental Assessment Method), una de las más usadas a nivel mundial junto a LEED."],
["GWP","Sustentabilidad y Medio Ambiente","Potencial de Calentamiento Global (Global Warming Potential): indicador que mide la contribución de un material o proceso al efecto invernadero, en equivalente de CO2."],
["WBLCA","Sustentabilidad y Medio Ambiente","Whole Building Life Cycle Assessment: análisis de ciclo de vida aplicado a la totalidad de un edificio, en vez de a un material o componente aislado."],
["Lean","Gestión y Administración de Obra","Filosofía de gestión orientada a maximizar el valor entregado al cliente minimizando el desperdicio de recursos, tiempo y esfuerzo; da origen a enfoques como Lean Construction y Lean Management."],
["BIM 4D","Software y herramientas digitales","Modelado BIM que incorpora la variable tiempo, vinculando el modelo tridimensional con la programación de obra."],
["Módulo de Elasticidad","Estructura","Propiedad de un material que relaciona el esfuerzo aplicado con la deformación que produce, dentro de su rango elástico; a mayor módulo, mayor rigidez."],
["Límite de Rotura","Estructura","Esfuerzo máximo que un material puede resistir antes de fracturarse o romperse."],
["Momento flector","Estructura","Solicitación que provoca la flexión de un elemento estructural, generando tracción en una cara y compresión en la opuesta."],
["Momento torsor","Estructura","Solicitación que provoca la torsión o giro de un elemento respecto a su eje longitudinal; también llamado torque."],
["Inercia","Estructura","Momento de inercia: propiedad geométrica de una sección que mide su resistencia a la flexión, según cómo se distribuye el área respecto a un eje."],
["PRC (Plan Regulador Comunal)","Normativa e instituciones","Instrumento de planificación territorial que regula el uso de suelo, densidad y edificación dentro de una comuna."],
["Plan Regulador Intercomunal (PRIC)","Normativa e instituciones","Instrumento de planificación territorial que coordina el desarrollo urbano de varias comunas que conforman una unidad geográfica."],
["Capacidad Portante","Geotecnia y topografía","Capacidad de un suelo para soportar cargas sin fallar. Se distingue la capacidad última (carga máxima antes de la falla) de la capacidad admisible (la última dividida por un factor de seguridad)."],
["Módulo de Terzaghi","Geotecnia y topografía","Módulo de balasto o reacción de subrasante, usado para estimar la respuesta de un suelo ante una carga aplicada, en el diseño de fundaciones y pavimentos."],
["Proctor Modificado","Ensayos de Obra","Ensayo que determina la densidad seca máxima y la humedad óptima de compactación de un suelo, usando mayor energía de compactación que el Proctor estándar."],
["Ensayo de Penetración Estándar (SPT)","Ensayos de Obra","Ensayo de terreno que mide la resistencia de un suelo al hincado de una cuchara normalizada, usado para estimar su capacidad portante."],
["Ensayo del Cono de Arena","Ensayos de Obra","Método para determinar la densidad in situ de un suelo compactado, reemplazando el volumen de una excavación con arena de densidad conocida (norma NCh 1516)."],
["Licuefacción del Suelo","Geotecnia y topografía","Fenómeno en que un suelo saturado pierde su resistencia y rigidez ante un sismo, comportándose temporalmente como un líquido."],
["Asentamiento Diferencial","Geotecnia y topografía","Hundimiento desigual entre distintos puntos de una fundación, que puede generar daños estructurales si supera los límites admisibles."],
["Asentamiento Uniforme","Geotecnia y topografía","Hundimiento parejo de toda una fundación, generalmente menos dañino que el asentamiento diferencial al no generar esfuerzos adicionales por distorsión."],
["Holgura","Gestión y Administración de Obra","Tiempo de margen (float o slack) que puede retrasarse una actividad de la programación sin afectar la fecha de término del proyecto."],
["Curva S","Gestión y Administración de Obra","Gráfico que representa el avance acumulado (físico o financiero) de un proyecto en el tiempo, con forma de S característica por el ritmo de inicio y cierre más lentos."],
["MS Project","Software y herramientas digitales","Software de Microsoft usado para planificar, programar y controlar el avance de proyectos mediante cartas Gantt y ruta crítica."],
["WBS / EDT (Estructura de Desglose del Trabajo)","Gestión y Administración de Obra","Descomposición jerárquica del trabajo total de un proyecto en partes más pequeñas y manejables, base para programar y presupuestar."],
["EVM (Gestión del Valor Ganado)","Gestión y Administración de Obra","Earned Value Management: metodología que compara el avance físico real de un proyecto contra lo planificado y lo gastado, para medir su desempeño en costo y plazo."],
["CBR (California Bearing Ratio)","Pavimentos","Ensayo que mide la capacidad de soporte de un suelo o material granular, usado principalmente para el diseño de pavimentos."],
["Encofrado","Faena y obra","Molde temporal, de madera o metal, que da forma al hormigón fresco hasta que este adquiere suficiente resistencia; también llamado moldaje."],
["LID (Low Impact Development)","Sustentabilidad y Medio Ambiente","Enfoque de diseño urbano que busca gestionar las aguas lluvias de forma similar a las condiciones naturales del terreno, reduciendo la escorrentía e infiltrando agua localmente."],
["Cortante Basal","Estructura","Fuerza horizontal total que un sismo genera en la base de una edificación, usada como parámetro clave en el diseño sismorresistente."],
["Ductilidad","Estructura","Capacidad de un material o elemento estructural de deformarse significativamente antes de fallar, disipando energía durante un sismo."],
["Grúa","Maquinaria","Equipo usado para izar, trasladar y posicionar cargas pesadas en altura durante la construcción."],
["Miniexcavadora","Maquinaria","Excavadora de tamaño reducido, usada en espacios acotados donde no cabe maquinaria de mayor tamaño."],
["Motoniveladora","Maquinaria","Maquinaria usada para nivelar y perfilar superficies de terreno, especialmente en la construcción de caminos."],
["Cargador","Maquinaria","Maquinaria con balde frontal usada para cargar, mover y apilar materiales sueltos como tierra, áridos o escombros."],
["Bulldozer","Maquinaria","Maquinaria de orugas con una hoja frontal, usada para empujar, nivelar y remover grandes volúmenes de tierra."],
["Camión dúmper","Maquinaria","Camión de tolva basculante usado para transportar y descargar áridos, tierra o escombros en obra."],
["Camión Pluma","Maquinaria","Camión equipado con una grúa articulada, usado para cargar y descargar materiales pesados en obra."],
["Pala punta de huevo","Herramientas","Pala con hoja curva y punta redondeada, usada para excavar en terrenos compactos."],
["Pala cuadrada","Herramientas","Pala de hoja plana y recta, usada principalmente para mezclar, cargar o traspalar materiales sueltos."],
["Pico","Herramientas","Herramienta de golpe con una punta y una pala en sus extremos (picota), usada para romper terrenos duros o pavimentos."],
["Martillo de carpintero","Herramientas","Martillo con una cabeza plana para golpear clavos y una uña posterior para extraerlos, de uso típico en carpintería."],
["Martillo de bola","Herramientas","Martillo con una cabeza plana y otra esférica, usado principalmente en trabajos de metalistería y remachado."],
["Cincel","Herramientas","Herramienta de hoja metálica y filo recto, golpeada con combo o martillo, usada para cortar o labrar piedra, hormigón o metal."],
["Palustre","Herramientas","Herramienta de hoja triangular usada para aplicar y extender mortero o estuco en muros."],
["Platacho","Herramientas","Herramienta de hoja plana rectangular usada para alisar y terminar superficies de hormigón o estuco."],
["Plomada","Herramientas","Instrumento formado por un peso colgado de una cuerda, usado para verificar la verticalidad (aplomado) de un elemento."],
["Flexómetro","Herramientas","Cinta métrica metálica y retráctil, usada para tomar medidas en terreno."],
["Serrucho","Herramientas","Herramienta manual de hoja dentada usada para cortar madera."],
["Ingleteadora","Herramientas","Sierra eléctrica que permite cortar piezas en ángulo con precisión, usada frecuentemente en terminaciones y carpintería."],
["Alicate","Herramientas","Herramienta manual usada para sujetar, doblar o cortar alambres y otros materiales delgados."],
["Martillo","Herramientas","Herramienta de golpe compuesta por una cabeza y un mango, usada principalmente para clavar o demoler elementos livianos; a diferencia del combo, tiene menor peso y se maneja con una sola mano."],
["Destornillador","Herramientas","Herramienta manual usada para apretar o aflojar tornillos, con punta plana o de cruz según el tipo de tornillo."],
["Atornillador","Herramientas","Herramienta eléctrica usada para apretar o aflojar tornillos de forma rápida, con menor potencia de impacto que un taladro percutor."],
["Sierra Caladora","Herramientas","Herramienta eléctrica con una hoja de corte vertical, usada para realizar cortes curvos o irregulares en madera, metal o plástico."],
["Lijadora Orbital","Herramientas","Herramienta eléctrica que lija superficies mediante un movimiento circular vibratorio, usada para pulir y preparar superficies antes de pintar."],
["Esmeril","Herramientas","Herramienta eléctrica con disco abrasivo giratorio, usada para cortar, pulir o desbastar metal, hormigón u otros materiales; también llamado galletero."],
["Remachadora","Herramientas","Herramienta usada para unir piezas metálicas mediante remaches, sin necesidad de soldadura."],
["Estática","Estructura","Rama de la mecánica que estudia los cuerpos en equilibrio, es decir, en reposo o con velocidad constante, analizando las fuerzas que actúan sobre ellos."],
["Cinemática","Estructura","Rama de la mecánica que describe el movimiento de los cuerpos (posición, velocidad, aceleración) sin considerar las fuerzas que lo provocan."],
["Dinámica estructural","Estructura","Rama de la ingeniería que estudia la respuesta de una estructura ante cargas variables en el tiempo, como sismos o viento."],
["Fuerza","Estructura","Acción capaz de modificar el estado de reposo o movimiento de un cuerpo, o de deformarlo; se representa mediante magnitud, dirección y sentido."],
["Vector fuerza","Estructura","Representación gráfica y matemática de una fuerza mediante una flecha, que indica su magnitud, dirección y punto de aplicación."],
["Equilibrio estático","Estructura","Condición en la que la suma de todas las fuerzas y momentos que actúan sobre un cuerpo es igual a cero, por lo que este permanece en reposo."],
["Reacción de apoyo","Estructura","Fuerza que ejerce un apoyo sobre una estructura para mantener su equilibrio, en respuesta a las cargas aplicadas sobre ella."],
["Carga puntual","Estructura","Fuerza que se aplica sobre un punto específico de un elemento estructural."],
["Carga distribuida","Estructura","Fuerza que se reparte a lo largo de una superficie o longitud de un elemento estructural, en vez de concentrarse en un punto."],
["Centro de gravedad","Estructura","Punto en el que se considera concentrado el peso total de un cuerpo, para efectos de análisis de equilibrio."],
["Esfuerzo normal","Estructura","Fuerza interna que actúa perpendicular a la sección transversal de un elemento, generando tracción o compresión."],
["Tensión admisible","Estructura","Esfuerzo máximo que se permite aplicar a un material en el diseño, considerando un margen de seguridad respecto a su resistencia real."],
["Coeficiente de seguridad","Estructura","Factor que relaciona la resistencia real de un elemento con la solicitación de diseño, para asegurar un margen ante incertidumbres o cargas imprevistas."],
["Rigidez estructural","Estructura","Capacidad de un elemento o sistema estructural de resistir deformaciones ante la aplicación de cargas."],
["Disipador sísmico","Estructura","Dispositivo que absorbe y disipa la energía generada por un sismo, reduciendo las deformaciones y daños en la estructura principal."],
["Aislador sísmico","Estructura","Dispositivo instalado entre la fundación y la superestructura de un edificio, que reduce la transmisión de las fuerzas sísmicas hacia la construcción."],
["Período fundamental","Estructura","Tiempo que demora una estructura en completar un ciclo de vibración libre en su modo más simple; parámetro clave del diseño sismorresistente."],
["Deriva de piso","Estructura","Desplazamiento horizontal relativo entre dos pisos consecutivos de un edificio durante un sismo, expresado como porcentaje de la altura de entrepiso."],
["Espectro de diseño","Estructura","Gráfico que representa la respuesta máxima esperada de una estructura ante un sismo, en función de su período, usado como base del diseño sismorresistente."],
["Amortiguamiento estructural","Estructura","Capacidad de una estructura de disipar energía y reducir la amplitud de sus vibraciones con el tiempo."],
["Factor de reducción sísmica","Estructura","Coeficiente que permite reducir las fuerzas sísmicas de diseño, considerando la capacidad de la estructura de disipar energía mediante comportamiento no lineal."],
["Junta sísmica","Estructura","Espacio de separación entre dos edificaciones o cuerpos de una misma estructura, que permite el desplazamiento independiente durante un sismo sin que choquen entre sí."],
["Análisis modal espectral","Estructura","Método de análisis sísmico que combina la respuesta de los distintos modos de vibración de una estructura frente a un espectro de diseño."],
["Panel fotovoltaico","Sustentabilidad y Medio Ambiente","Dispositivo que convierte la energía solar directamente en electricidad mediante celdas fotovoltaicas."],
["Panel Solar","Sustentabilidad y Medio Ambiente","Término genérico para dispositivos que captan energía solar; incluye tanto los paneles fotovoltaicos (generan electricidad) como los colectores solares térmicos (calientan agua)."],
["Hormigón Proyectado (Shotcrete)","Faena y obra","Técnica de aplicación de hormigón mediante proyección a alta velocidad sobre una superficie, usada en taludes, túneles y reparaciones estructurales."],
["Steel Framing","Tipos de obra","Sistema constructivo basado en perfiles de acero galvanizado liviano, usado como estructura de muros y entrepisos en reemplazo de la madera o el hormigón."]
["Memorias de Cálculo","Estructura","Documento que respalda y justifica los cálculos estructurales, hidráulicos o eléctricos utilizados en el diseño de un proyecto."]
];
